name: Send message to girlfriend

on:
  schedule:
    - cron: '0 0 * * *' # 每天早上 0 点

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies and run Python script
        run: |
          npm install
          python main.py
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          USER_ID: ${{ secrets.USER_ID }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY: ${{ secrets.BIRTHDAY }}
          CITY: ${{ secrets.CITY }}
          CITY_ID: ${{ secrets.CITY_ID }}
